name: Formatting and Tests

on:
    - pull_request
    - push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Pytest and Black formatting

        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.6, 3.7, 3.8, 3.9, 3.10]

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install

            - name: Check Formatting
              run: | 
                black --check .
                flake8 .
                isort --check .

            - name: Run Tests
              run: pytest
